name: React Native CD

on:
  push:
    branches:
      - main

jobs:
  deploy_beta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 🛒
        uses: actions/checkout@v2

      - name: Set up Ruby 💎
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install Fastlane 🏎️
        run: gem install fastlane

      - name: iOS Beta Deployment 🖥️✈️
        run: fastlane ios beta
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}

      - name: Android Beta Deployment 🤖✈️
        run: fastlane android beta
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
