name: Dependabot 🦾

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 3
      # Add additional reviewers for dependabot PRs (not in CODEOWNERS) e.g,
      # reviewers:
      #   - "johndoe"
