# TODO: Use bundle exec for fastlane and gemfile
name: Deploy Production Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  setup:
    name: "Setup: Installing dependencies 🛒"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 🛒
        uses: actions/checkout@v2

      - name: Set up Ruby Environment 💎
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Cache Ruby Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Dependencies via Bundler 📦
        run: bundle install

  ios_production:
    name: "Deployment: Deploying iOS Production Release 🖥️🚀"
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 🛒
        uses: actions/checkout@v2

      - name: Restore Ruby Cache 💎
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: iOS Production Deployment 🖥️🚀
        run: bundle exec fastlane ios release
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

  android_production:
    name: "Deployment: Deploying Android Production Release 🤖🚀"
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 🛒
        uses: actions/checkout@v2

      - name: Restore Ruby Cache 💎
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Android Production Deployment 🤖🚀
        run: bundle exec fastlane android release
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          JSON_KEY_DATA: ${{ secrets.JSON_KEY_DATA }}
