name: Deploy Production Release

on:
  push:
    tags:
      - '*'

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 🛒
        uses: actions/checkout@v2

      - name: Set up Ruby 💎
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install Fastlane 🏎️
        run: gem install fastlane

      - name: iOS Production Deployment 🖥️🚀
        run: fastlane ios release
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - name: Android Production Deployment 🤖🚀
        run: fastlane android release
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          JSON_KEY_DATA: ${{ secrets.JSON_KEY_DATA }}
